---
# tasks file for apigee-opdk-setup-bootstrap-rollback
- name: Gracefully Stop apigee components, if possible
  ignore_errors: yes
  shell: '{{ apigee_all }} stop'

- name: Clear all artifacts from YUM repo
  become: yes
  ignore_errors: yes
  shell: 'yum clean all'

- name: Remove apigee, edge, baas and qpid packages
  become: yes
  ignore_errors: yes
  yum:
    name: '{{ item }}'
    state: absent
  with_items:
  - apigee-*
  - edge-*
  - baas-*
  - qpid-*
  - python-qpid-*
  - libdb-cxx-*
  - nginx-*

- name: Set target bootstrap script name for 4.16.01
  set_fact:
    bootstrap_script: '{{ opdk_installer_path }}/bootstrap.sh'
  when: opdk_version | version_compare('4.16.01', '==')

- name: Set target bootstrap script name for version > 4.16.01
  set_fact:
    bootstrap_script: '{{ opdk_installer_path }}/bootstrap_{{ opdk_version }}.sh'
  when: opdk_version | version_compare('4.16.01', '>')

- name: Remove bootstrap script and folders
  ignore_errors: yes
  file:
    path: '{{ item }}'
    state: absent
    follow: yes
  with_items:
  - '{{ bootstrap_script }}'
  - '{{ linked_apigee_installation_home }}'
  - /opt/nginx/conf.d
  - '{{ opdk_installation_config_file }}'
  - '{{ apigee_validate_config_file }}'
  - '{{ onboarding_config_file_path }}'

- name: Remove /opt/apigee on rolback
  ignore_errors: yes
  file:
    path: '{{ item }}'
    state: absent
    follow: yes
  with_items:
  - '{{ apigee_installation_home }}'
  when: remove_apigee is defined and remove_apigee

- name: Determine current user
  shell: whoami
  register: whoami

- name: Determine if safe to kill user owned process
  set_fact:
    kill_user: '{{ whoami.stdout != opdk_user_name }}'
  when: remove_apigee is defined and remove_apigee

- name: Release any apigee user owned processes
  become: yes
  shell: 'pkill -u {{ opdk_user_name }}'
  ignore_errors: yes
  when: kill_user
  async: 45
  poll: 0
  when: remove_apigee is defined and remove_apigee

- name: Remove apigee user
  become: yes
  ignore_errors: yes
  user:
    name: "{{ opdk_user_name }}"
    remove: yes
    state: absent
  async: 45
  poll: 0
  when: remove_apigee is defined and remove_apigee

- name: Remove the apigee group
  become: yes
  ignore_errors: yes
  group:
    name: "{{ opdk_group_name }}"
    state: absent
  async: 45
  poll: 0
  when: remove_apigee is defined and remove_apigee
