---
# tasks file for opdk-setup-bootstrap-rollback
- name: Gracefully Stop apigee components, if possible
  shell: '{{ apigee_all }} stop'
  ignore_errors: yes

- name: Clear all artifacts from YUM repo
  shell: 'yum clean all'
  ignore_errors: yes

- name: Remove apigee, edge, baas and qpid packages
  ignore_errors: yes
  yum:
    name: '{{ item }}'
    state: absent
  with_items:
  - apigee-*
  - edge-*
  - baas-*
  - qpid-*
  - python-qpid-*
  - libdb-cxx-*
  - nginx-*

- name: Set target bootstrap script name for 4.16.01
  set_fact:
    bootstrap_script: '{{ opdk_installer_path }}/bootstrap.sh'
  when: opdk_version | version_compare('4.16.01', '==')

- name: Set target bootstrap script name for 4.16.05
  set_fact:
    bootstrap_script: '{{ opdk_installer_path }}/bootstrap_{{ opdk_version }}.sh'
  when: opdk_version | version_compare('4.16.01', '>')

- name: Remove bootstrap script and folders
  ignore_errors: yes
  file:
    path: '{{ item }}'
    state: absent
    follow: yes
  with_items:
  - '{{ bootstrap_script }}'
  - '{{ linked_apigee_installation_home }}'
  - /opt/nginx

- name: Remove analytics data on rolback
  ignore_errors: yes
  file:
    path: '{{ item }}'
    state: absent
    follow: yes
  with_items:
  - '{{ apigee_installation_home }}/data'
  - '/opt/nginx'
  when: remove_data_on_rollback is defined and remove_data_on_rollback

- name: Determine current user
  shell: whoami
  register: whoami

- name: Determine if safe to kill user owned process
  set_fact:
    kill_user: '{{ whoami.stdout != opdk_user_name }}'

- name: Release any apigee user owned processes
  shell: 'pkill -u {{ opdk_user_name }}'
  ignore_errors: yes
  when: kill_user
  async: 45
  poll: 0

  - name: Create the apigee user
    user:
      name: "{{ opdk_user_name }}"
      remove: yes
      state: absent

- name: Remove apigee user
  - name: Create the apigee group
    group:
      name: "{{ opdk_group_name }}"
      state: absent


